package Forms;

import java.sql.*; 
import javax.swing.*; 
import java.util.*;
import java.util.logging.*;
import misc.*;
import properties.*;

public class datapaket extends javax.swing.JFrame {

    /**
     * Creates new form dataBuku
     */
    public datapaket() throws Exception{
        initComponents();
        inits();
    }
    
    static String idpgwi, commit;
    int posX = 0, posY = 0;
    private final Connection conn = koneksi.getDatabase(); 
    Statement st;
    ResultSet rs;
    static Object[] Baris = {"ID Paket", "Nama Paket", "Kecepatan", "Harga"};
    
    private void inits(){
        namaPaket.requestFocus();
        TableProperties.initTable(Baris, tabelPaket);
        TableProperties.getColumns("SELECT * FROM data_paket");
        TableProperties.showData(Baris, tabelPaket, "SELECT * FROM data_paket");
        kosong();
    }

    protected void kosong(){
        AutoId.getId(Idpaket, "normal", "data_paket", "id_paket", "Pkt");
        namaPaket.setText(""); 
        kecepatan.setText("");
        harga.setText("");           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPaket = new javax.swing.JTable();
        btnbatal = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        namaPaket = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        minimize = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        searchTrans = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Idpaket = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        kecepatan = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(768, 500));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(null);

        tabelPaket.setForeground(new java.awt.Color(87, 131, 123));
        tabelPaket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID KARYAWAN", "NAMA", "USERNAME", "PASSWORD"
            }
        ));
        tabelPaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPaketMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelPaket);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(330, 150, 420, 280);

        btnbatal.setBackground(new java.awt.Color(0, 153, 204));
        btnbatal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnbatal.setForeground(new java.awt.Color(244, 244, 244));
        btnbatal.setText("Batal");
        btnbatal.setBorder(null);
        btnbatal.setPreferredSize(new java.awt.Dimension(110, 40));
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });
        jPanel3.add(btnbatal);
        btnbatal.setBounds(60, 440, 100, 40);

        btnhapus.setBackground(new java.awt.Color(198, 71, 86));
        btnhapus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnhapus.setForeground(new java.awt.Color(244, 244, 244));
        btnhapus.setText("Hapus");
        btnhapus.setBorder(null);
        btnhapus.setPreferredSize(new java.awt.Dimension(110, 40));
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel3.add(btnhapus);
        btnhapus.setBounds(170, 440, 100, 40);

        btnsimpan.setBackground(new java.awt.Color(0, 153, 204));
        btnsimpan.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnsimpan.setForeground(new java.awt.Color(244, 244, 244));
        btnsimpan.setText("Simpan");
        btnsimpan.setBorder(null);
        btnsimpan.setPreferredSize(new java.awt.Dimension(110, 40));
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel3.add(btnsimpan);
        btnsimpan.setBounds(100, 370, 140, 50);

        namaPaket.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        namaPaket.setForeground(new java.awt.Color(87, 131, 123));
        namaPaket.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(87, 131, 123)));
        namaPaket.setPreferredSize(new java.awt.Dimension(156, 22));
        jPanel3.add(namaPaket);
        namaPaket.setBounds(140, 190, 150, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(87, 131, 123));
        jLabel3.setText("Nama Paket");
        jLabel3.setPreferredSize(new java.awt.Dimension(140, 22));
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 190, 110, 22);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(87, 131, 123));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DATA PAKET");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 92, 103)));
        jPanel3.add(jLabel5);
        jLabel5.setBounds(100, 50, 600, 40);

        jPanel5.setBackground(new java.awt.Color(0, 153, 204));
        jPanel5.setPreferredSize(new java.awt.Dimension(768, 40));
        jPanel5.setLayout(null);

        minimize.setBackground(new java.awt.Color(0, 153, 204));
        minimize.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        minimize.setForeground(java.awt.Color.white);
        minimize.setText("-");
        minimize.setBorderPainted(false);
        minimize.setFocusable(false);
        minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeActionPerformed(evt);
            }
        });
        jPanel5.add(minimize);
        minimize.setBounds(670, 0, 50, 40);

        exit.setBackground(new java.awt.Color(0, 153, 204));
        exit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        exit.setForeground(java.awt.Color.white);
        exit.setText("X");
        exit.setBorderPainted(false);
        exit.setFocusable(false);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel5.add(exit);
        exit.setBounds(720, 0, 50, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sistem Administrasi");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(0, 0, 150, 40);

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText(userSession.getNama());
        jPanel5.add(jLabel8);
        jLabel8.setBounds(160, 0, 130, 40);

        jSeparator2.setForeground(java.awt.Color.white);
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator2);
        jSeparator2.setBounds(150, 7, 10, 25);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(0, 0, 768, 40);

        jLabel29.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(87, 131, 123));
        jLabel29.setText(":");
        jPanel3.add(jLabel29);
        jLabel29.setBounds(450, 110, 10, 30);

        jLabel32.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(87, 131, 123));
        jLabel32.setText("Cari Paket");
        jPanel3.add(jLabel32);
        jLabel32.setBounds(330, 110, 130, 30);

        searchTrans.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        searchTrans.setForeground(new java.awt.Color(87, 131, 123));
        searchTrans.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(87, 131, 123)));
        searchTrans.setPreferredSize(new java.awt.Dimension(55, 30));
        searchTrans.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTransKeyReleased(evt);
            }
        });
        jPanel3.add(searchTrans);
        searchTrans.setBounds(460, 110, 220, 30);

        jSeparator1.setBackground(new java.awt.Color(51, 92, 103));
        jSeparator1.setForeground(new java.awt.Color(87, 131, 123));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(310, 110, 10, 390);

        Idpaket.setEditable(false);
        Idpaket.setBackground(new java.awt.Color(255, 255, 255));
        Idpaket.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Idpaket.setForeground(new java.awt.Color(87, 131, 123));
        Idpaket.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(87, 131, 123)));
        Idpaket.setFocusable(false);
        Idpaket.setPreferredSize(new java.awt.Dimension(156, 22));
        jPanel3.add(Idpaket);
        Idpaket.setBounds(140, 160, 150, 22);

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(87, 131, 123));
        jLabel9.setText("ID Paket");
        jLabel9.setPreferredSize(new java.awt.Dimension(140, 22));
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 160, 110, 22);

        kecepatan.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        kecepatan.setForeground(new java.awt.Color(87, 131, 123));
        kecepatan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(87, 131, 123)));
        kecepatan.setPreferredSize(new java.awt.Dimension(156, 22));
        jPanel3.add(kecepatan);
        kecepatan.setBounds(140, 220, 150, 20);

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(87, 131, 123));
        jLabel12.setText("Kecepatan");
        jLabel12.setPreferredSize(new java.awt.Dimension(140, 22));
        jPanel3.add(jLabel12);
        jLabel12.setBounds(20, 220, 110, 20);

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(87, 131, 123));
        jLabel13.setText("Harga");
        jLabel13.setPreferredSize(new java.awt.Dimension(140, 22));
        jPanel3.add(jLabel13);
        jLabel13.setBounds(20, 250, 110, 20);

        harga.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        harga.setForeground(new java.awt.Color(87, 131, 123));
        harga.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(87, 131, 123)));
        harga.setPreferredSize(new java.awt.Dimension(156, 22));
        jPanel3.add(harga);
        harga.setBounds(140, 250, 150, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(768, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelPaketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPaketMouseClicked
        int bar = tabelPaket.getSelectedRow();
        Idpaket.setText(tabelPaket.getValueAt(bar, 0).toString());
        namaPaket.setText(tabelPaket.getValueAt(bar, 1).toString());
        kecepatan.setText(tabelPaket.getValueAt(bar, 2).toString());
        harga.setText(tabelPaket.getValueAt(bar, 3).toString());
    }//GEN-LAST:event_tabelPaketMouseClicked

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        inits();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        int bar = tabelPaket.getSelectedRow();
        int ok = JOptionPane.showConfirmDialog(null, "hapus","Konfirmasi Dialog",
            JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0){
            String sql = "delete from data_paket where id_paket='"+tabelPaket.getValueAt(bar, 0)+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                kosong();
                namaPaket.requestFocus();
                inits();
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus" +e);
            }
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        if (Idpaket.getText().length() == 0 || namaPaket.getText().length() == 0 ||
            kecepatan.getText().length() == 0 || harga.getText().length() == 0){
            JOptionPane.showMessageDialog(this, "jangan kosong", "Pesan", JOptionPane.ERROR_MESSAGE);
        }else{
            Object[] values = {Idpaket.getText(), namaPaket.getText(),
                kecepatan.getText(), harga.getText()};

            String sql = "SELECT * FROM data_paket WHERE id_paket = '"+Idpaket.getText()+"'";
            commit = OlahData.commit(sql);
            try {
                if(commit.equals("update")){
                    OlahData.saveUpdate("normal",
                        "update data_paket set id_paket=?, nama=?, kecepatan=?, harga=? where id_paket='"+Idpaket.getText()+"'",
                        values);
                }else if(commit.equals("save")){
                    OlahData.saveUpdate("normal", "INSERT INTO data_paket VALUE (?,?,?,?)", values);
                    
                }
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");

                inits();
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Warning", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(datapaket.class.getName()).log(Level.SEVERE, null, e);
            }
            sql = null;
            commit = null;
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeActionPerformed
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        dispose();
        try {
            new menu_utama().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(menu_utama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_exitActionPerformed

    private void searchTransKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTransKeyReleased
        String search = searchTrans.getText();
        String query = "SELECT * FROM data_paket WHERE id_paket LIKE '%"+search+"%' "
        + "OR nama LIKE '%"+search+"%' "
        + "OR kecepatan LIKE '%"+search+"%' "
        + "OR harga LIKE '%"+search+"%' ";
        
        TableProperties.getColumns(query);
        TableProperties.showData(Baris, tabelPaket, query);
    }//GEN-LAST:event_searchTransKeyReleased

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        // TODO add your handling code here:
        setLocation (evt.getXOnScreen()-posX,evt.getYOnScreen()-posY);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        posX = evt.getX();
        posY = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datapaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datapaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datapaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datapaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new datapaket().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(datapaket.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Idpaket;
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton exit;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField kecepatan;
    private javax.swing.JButton minimize;
    private javax.swing.JTextField namaPaket;
    private javax.swing.JTextField searchTrans;
    private javax.swing.JTable tabelPaket;
    // End of variables declaration//GEN-END:variables
}
