package Forms;

//imports
import java.awt.Toolkit;
import java.sql.*;
import java.text.*;
import javax.swing.*;
import misc.*;
import java.util.logging.*;
import properties.*;

public class newUser extends javax.swing.JFrame {

    /**
     * Creates new form newUser
     */
    public newUser() throws Exception{
        initComponents();
        AutoId.getId(iKodeUser, "normal", "pegawai", "id_pegawai", "PE");
        System.out.println(iKodeUser.getText());
    }
    
//    Global variables
    String commit;
    DateFormat dateFormat = new SimpleDateFormat("YYYY-MM-dd");
    Connection conn = koneksi.getDatabase();
    Statement st;
    ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        close = new javax.swing.JButton();
        minimize = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        iKodeUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        iNamaUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        iNotelp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        iAlamatUser = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        bSaveUser = new javax.swing.JButton();
        showPass = new javax.swing.JToggleButton();
        iPassword = new javax.swing.JPasswordField();
        jLabel45 = new javax.swing.JLabel();
        iJabatan = new javax.swing.JTextField();
        lakik = new javax.swing.JRadioButton();
        perempuan = new javax.swing.JRadioButton();
        iUsername = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        close.setBackground(new java.awt.Color(0, 153, 204));
        close.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        close.setForeground(new java.awt.Color(245, 245, 245));
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-close-25.png"))); // NOI18N
        close.setBorder(null);
        close.setBorderPainted(false);
        close.setFocusable(false);
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        minimize.setBackground(new java.awt.Color(0, 153, 204));
        minimize.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        minimize.setForeground(new java.awt.Color(245, 245, 245));
        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-subtract-25.png"))); // NOI18N
        minimize.setBorder(null);
        minimize.setBorderPainted(false);
        minimize.setFocusable(false);
        minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(245, 245, 245));
        jLabel4.setText("Buat User Baru");
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(minimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(23, 23, 23));
        jLabel1.setText("Kode User");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));

        iKodeUser.setEditable(false);
        iKodeUser.setBackground(new java.awt.Color(255, 255, 255));
        iKodeUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        iKodeUser.setForeground(new java.awt.Color(23, 23, 23));
        iKodeUser.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(23, 23, 23)), javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0)));
        iKodeUser.setCaretColor(new java.awt.Color(23, 23, 23));
        iKodeUser.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(23, 23, 23));
        jLabel2.setText("Nama Lengkap");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));

        iNamaUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        iNamaUser.setForeground(new java.awt.Color(23, 23, 23));
        iNamaUser.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(23, 23, 23)), javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0)));
        iNamaUser.setCaretColor(new java.awt.Color(23, 23, 23));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(23, 23, 23));
        jLabel3.setText("Jenis Kelamin");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(23, 23, 23));
        jLabel5.setText("Nomor Telepon");
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));

        iNotelp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        iNotelp.setForeground(new java.awt.Color(23, 23, 23));
        iNotelp.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(23, 23, 23)), javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0)));
        iNotelp.setCaretColor(new java.awt.Color(23, 23, 23));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(23, 23, 23));
        jLabel6.setText("Alamat");
        jLabel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));

        jScrollPane1.setBackground(java.awt.Color.white);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        iAlamatUser.setColumns(20);
        iAlamatUser.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        iAlamatUser.setLineWrap(true);
        iAlamatUser.setRows(5);
        iAlamatUser.setWrapStyleWord(true);
        iAlamatUser.setCaretColor(new java.awt.Color(23, 23, 23));
        iAlamatUser.setPreferredSize(new java.awt.Dimension(280, 70));
        jScrollPane1.setViewportView(iAlamatUser);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(23, 23, 23));
        jLabel7.setText("Password");
        jLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));

        bSaveUser.setBackground(new java.awt.Color(0, 153, 204));
        bSaveUser.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        bSaveUser.setForeground(new java.awt.Color(245, 245, 245));
        bSaveUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-save-30(1).png"))); // NOI18N
        bSaveUser.setText("Simpan");
        bSaveUser.setBorder(null);
        bSaveUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSaveUser.setFocusable(false);
        bSaveUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveUserActionPerformed(evt);
            }
        });

        showPass.setBackground(java.awt.Color.white);
        showPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-eye-25 black.png"))); // NOI18N
        showPass.setBorder(null);
        showPass.setContentAreaFilled(false);
        showPass.setFocusable(false);
        showPass.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-hide-24 black.png"))); // NOI18N
        showPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassActionPerformed(evt);
            }
        });

        iPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        iPassword.setForeground(new java.awt.Color(32, 23, 23));
        iPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(23, 23, 23)));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(23, 23, 23));
        jLabel45.setText("Jabatan");
        jLabel45.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));

        iJabatan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        iJabatan.setForeground(new java.awt.Color(23, 23, 23));
        iJabatan.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(23, 23, 23)), javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0)));
        iJabatan.setCaretColor(new java.awt.Color(23, 23, 23));

        lakik.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(lakik);
        lakik.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lakik.setForeground(new java.awt.Color(23, 23, 23));
        lakik.setText("Laki-Laki");
        lakik.setFocusable(false);

        perempuan.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(perempuan);
        perempuan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        perempuan.setForeground(new java.awt.Color(23, 23, 23));
        perempuan.setText("Perempuan");
        perempuan.setFocusable(false);

        iUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        iUsername.setForeground(new java.awt.Color(23, 23, 23));
        iUsername.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(23, 23, 23)), javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0)));
        iUsername.setCaretColor(new java.awt.Color(23, 23, 23));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(23, 23, 23));
        jLabel8.setText("Username");
        jLabel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(iKodeUser)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(iJabatan))
                        .addGap(13, 13, 13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lakik)
                        .addGap(18, 18, 18)
                        .addComponent(perempuan)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bSaveUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(iNamaUser)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(iPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(iNotelp)
                                    .addComponent(iUsername))))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iKodeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iNamaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lakik, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(perempuan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iNotelp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bSaveUser, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(450, 688));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        try {
            dispose();
            new login().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(newUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_closeActionPerformed

    private void minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeActionPerformed
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeActionPerformed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        WindowProperties.setWinPosition(this, evt);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        WindowProperties.getWinPosition(evt);
    }//GEN-LAST:event_jPanel2MousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/logoLaundrySMOLLL.png")));
    }//GEN-LAST:event_formWindowOpened

    private void showPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassActionPerformed
        if(showPass.isSelected()){
            iPassword.setEchoChar((char)0); 
        }else{
            iPassword.setEchoChar('\u25cf');
        }
    }//GEN-LAST:event_showPassActionPerformed

    private void bSaveUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveUserActionPerformed
        if (iKodeUser.getText().length() == 0 || iNamaUser.getText().length() == 0 || 
                iNotelp.getText().length() == 0 || iAlamatUser.getText().length() == 0 || new String(iPassword.getPassword()).length() == 0) {
            JOptionPane.showMessageDialog(this, "jangan kosong", "Pesan", JOptionPane.ERROR_MESSAGE);
        }else{
            String jenkel;
            if (lakik.isSelected()) {
                jenkel = lakik.getText();
            }else{
                jenkel = perempuan.getText();
            }
           Object[] values = {iKodeUser.getText(), iNamaUser.getText(), jenkel,
                iJabatan.getText(), iNotelp.getText(), iAlamatUser.getText(), iUsername.getText(), new String(iPassword.getPassword())};
            
            String sql = "SELECT * FROM pegawai WHERE id_pegawai = '"+iKodeUser.getText()+"'";
            commit = OlahData.commit(sql);
            try {
                if(commit.equals("update")){
                    OlahData.saveUpdate("normal",
                        "update pegawai set id_pegawai=?, nama=?, jabatan=?,  notelp=?, alamat=?, username=?, password=? where id_user='"+iKodeUser.getText()+"'",
                        values);
                }else if(commit.equals("save")){
                    OlahData.saveUpdate("normal", "INSERT INTO pegawai VALUE (?,?,?,?,?,?,?,?)", values);
                }
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                
                iKodeUser.setText("");
                iNamaUser.setText("");
                iJabatan.setText("");
                iNotelp.setText("");
                iAlamatUser.setText("");
                iUsername.setText("");
                iPassword.setText("");
                
                dispose();
                new login().setVisible(true);
                login.username.setText(values[6].toString());
                login.pw.setText(values[7].toString());
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Warning", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(newUser.class.getName()).log(Level.SEVERE, null, e);
            }
            commit = null;
        }
    }//GEN-LAST:event_bSaveUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new newUser().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(newUser.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSaveUser;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton close;
    private javax.swing.JTextArea iAlamatUser;
    private javax.swing.JTextField iJabatan;
    private javax.swing.JTextField iKodeUser;
    private javax.swing.JTextField iNamaUser;
    private javax.swing.JTextField iNotelp;
    private javax.swing.JPasswordField iPassword;
    private javax.swing.JTextField iUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton lakik;
    private javax.swing.JButton minimize;
    private javax.swing.JRadioButton perempuan;
    private javax.swing.JToggleButton showPass;
    // End of variables declaration//GEN-END:variables
}
