package Forms;

import java.sql.*; 
import java.text.*;
import javax.swing.*; 
import java.util.*;
import java.util.logging.*;
import misc.*;
import properties.*;

public class pembayaran extends javax.swing.JFrame {

    /**
     * Creates new form pembayaran
     */
    public pembayaran() throws Exception{
        initComponents();
        inits();
        
    }
    
    static String idpgwi, commit;
    static String Idbayar = AutoId.setId("Pb", "pembayaran", "id_pembayaran");
    DateFormat dateFormat = new SimpleDateFormat("YYYY-MM-dd");
    int posX = 0, posY = 0;
    private final Connection conn = koneksi.getDatabase(); 
    Statement st;
    ResultSet rs;
    Object[] Baris = {"ID Pembayaran", "ID Pelanggan", "Nama", "Tanggal", "Tenggat","Total"};
    
    private void inits(){
        namaPelanggan.requestFocus();
        TableProperties.initTable(Baris, tabelBayar);
        TableProperties.getColumns("SELECT * FROM pembayaran");
        TableProperties.showData(Baris, tabelBayar, "SELECT * FROM pembayaran");
        kosong();
    }

    protected void kosong(){
        IDpelanggan.setText("");
        namaPelanggan.setText("");
        tenggat.setText("");
        totalbayar.setText("");
                  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelBayar = new javax.swing.JTable();
        btnbatal = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        namaPelanggan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        minimize = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        IDpelanggan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tglBayar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        IDpembayaran = new javax.swing.JTextField();
        totalbayar = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tenggat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(768, 500));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(null);

        tabelBayar.setForeground(new java.awt.Color(87, 131, 123));
        tabelBayar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Pembayaran", "ID Pelanggan", "Nama", "Tanggal", "Tenggat"
            }
        ));
        tabelBayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBayarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelBayar);
        tabelBayar.getAccessibleContext().setAccessibleName("\n");

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(400, 110, 350, 200);

        btnbatal.setBackground(new java.awt.Color(0, 153, 204));
        btnbatal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnbatal.setForeground(new java.awt.Color(244, 244, 244));
        btnbatal.setText("Batal");
        btnbatal.setBorder(null);
        btnbatal.setPreferredSize(new java.awt.Dimension(110, 40));
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });
        jPanel3.add(btnbatal);
        btnbatal.setBounds(70, 500, 110, 40);

        btnhapus.setBackground(new java.awt.Color(198, 71, 86));
        btnhapus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnhapus.setForeground(new java.awt.Color(244, 244, 244));
        btnhapus.setText("Hapus");
        btnhapus.setBorder(null);
        btnhapus.setPreferredSize(new java.awt.Dimension(110, 40));
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel3.add(btnhapus);
        btnhapus.setBounds(190, 500, 110, 40);

        btnsimpan.setBackground(new java.awt.Color(0, 153, 204));
        btnsimpan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnsimpan.setForeground(new java.awt.Color(244, 244, 244));
        btnsimpan.setText("Tambah");
        btnsimpan.setBorder(null);
        btnsimpan.setPreferredSize(new java.awt.Dimension(110, 40));
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel3.add(btnsimpan);
        btnsimpan.setBounds(130, 450, 110, 40);

        namaPelanggan.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        namaPelanggan.setForeground(new java.awt.Color(87, 131, 123));
        namaPelanggan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(87, 131, 123)));
        namaPelanggan.setFocusable(false);
        namaPelanggan.setPreferredSize(new java.awt.Dimension(156, 22));
        jPanel3.add(namaPelanggan);
        namaPelanggan.setBounds(180, 170, 180, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(87, 131, 123));
        jLabel3.setText("Nama Pelanggan");
        jLabel3.setPreferredSize(new java.awt.Dimension(140, 22));
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 170, 160, 22);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(87, 131, 123));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PEMBAYARAN");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 92, 103)));
        jPanel3.add(jLabel5);
        jLabel5.setBounds(100, 50, 600, 40);

        jPanel5.setBackground(new java.awt.Color(0, 153, 204));
        jPanel5.setPreferredSize(new java.awt.Dimension(768, 40));
        jPanel5.setLayout(null);

        minimize.setBackground(new java.awt.Color(0, 153, 204));
        minimize.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        minimize.setForeground(java.awt.Color.white);
        minimize.setText("-");
        minimize.setBorderPainted(false);
        minimize.setFocusable(false);
        minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeActionPerformed(evt);
            }
        });
        jPanel5.add(minimize);
        minimize.setBounds(670, 0, 50, 40);

        exit.setBackground(new java.awt.Color(0, 153, 204));
        exit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        exit.setForeground(java.awt.Color.white);
        exit.setText("X");
        exit.setBorderPainted(false);
        exit.setFocusable(false);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel5.add(exit);
        exit.setBounds(720, 0, 50, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sistem Administrasi");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(0, 0, 150, 40);

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText(userSession.getNama());
        jPanel5.add(jLabel8);
        jLabel8.setBounds(160, 0, 130, 40);

        jSeparator2.setForeground(java.awt.Color.white);
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator2);
        jSeparator2.setBounds(150, 7, 10, 25);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(0, 0, 768, 40);

        jSeparator1.setBackground(new java.awt.Color(51, 92, 103));
        jSeparator1.setForeground(new java.awt.Color(87, 131, 123));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(380, 100, 10, 440);

        IDpelanggan.setEditable(false);
        IDpelanggan.setBackground(new java.awt.Color(255, 255, 255));
        IDpelanggan.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        IDpelanggan.setForeground(new java.awt.Color(87, 131, 123));
        IDpelanggan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(87, 131, 123)));
        IDpelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IDpelanggan.setFocusable(false);
        IDpelanggan.setPreferredSize(new java.awt.Dimension(156, 22));
        IDpelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IDpelangganMouseClicked(evt);
            }
        });
        IDpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDpelangganActionPerformed(evt);
            }
        });
        jPanel3.add(IDpelanggan);
        IDpelanggan.setBounds(180, 140, 180, 22);

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(87, 131, 123));
        jLabel9.setText("ID Pelanggan");
        jLabel9.setPreferredSize(new java.awt.Dimension(140, 22));
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 140, 160, 22);

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(87, 131, 123));
        jLabel14.setText("Tanggal Bayar");
        jLabel14.setPreferredSize(new java.awt.Dimension(140, 22));
        jPanel3.add(jLabel14);
        jLabel14.setBounds(20, 200, 160, 20);

        tglBayar.setEditable(false);
        tglBayar.setBackground(new java.awt.Color(255, 255, 255));
        tglBayar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        tglBayar.setForeground(new java.awt.Color(87, 131, 123));
        tglBayar.setText(dateTime.getTanggal());
        tglBayar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(87, 131, 123)));
        tglBayar.setFocusable(false);
        tglBayar.setPreferredSize(new java.awt.Dimension(156, 22));
        jPanel3.add(tglBayar);
        tglBayar.setBounds(180, 200, 180, 20);

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(87, 131, 123));
        jLabel15.setText("Total Bayar");
        jLabel15.setPreferredSize(new java.awt.Dimension(140, 22));
        jPanel3.add(jLabel15);
        jLabel15.setBounds(20, 270, 160, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(87, 131, 123));
        jLabel10.setText("ID Pembayaran");
        jLabel10.setPreferredSize(new java.awt.Dimension(140, 22));
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 100, 160, 30);

        IDpembayaran.setEditable(false);
        IDpembayaran.setBackground(new java.awt.Color(255, 255, 255));
        IDpembayaran.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        IDpembayaran.setForeground(new java.awt.Color(87, 131, 123));
        IDpembayaran.setText(Idbayar);
        IDpembayaran.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(87, 131, 123)));
        IDpembayaran.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IDpembayaran.setFocusable(false);
        IDpembayaran.setPreferredSize(new java.awt.Dimension(156, 22));
        IDpembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDpembayaranActionPerformed(evt);
            }
        });
        jPanel3.add(IDpembayaran);
        IDpembayaran.setBounds(180, 100, 180, 30);

        totalbayar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        totalbayar.setForeground(new java.awt.Color(87, 131, 123));
        totalbayar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(87, 131, 123)));
        totalbayar.setPreferredSize(new java.awt.Dimension(156, 22));
        jPanel3.add(totalbayar);
        totalbayar.setBounds(180, 270, 180, 22);

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(87, 131, 123));
        jLabel16.setText("Tenggat Waktu");
        jLabel16.setPreferredSize(new java.awt.Dimension(140, 22));
        jPanel3.add(jLabel16);
        jLabel16.setBounds(20, 230, 160, 30);

        tenggat.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        tenggat.setForeground(new java.awt.Color(87, 131, 123));
        tenggat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(87, 131, 123)));
        tenggat.setPreferredSize(new java.awt.Dimension(156, 22));
        jPanel3.add(tenggat);
        tenggat.setBounds(180, 230, 180, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(768, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelBayarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBayarMouseClicked
        int bar = tabelBayar.getSelectedRow();
        IDpembayaran.setText(tabelBayar.getValueAt(bar, 0).toString());
        IDpelanggan.setText(tabelBayar.getValueAt(bar, 1).toString());
        namaPelanggan.setText(tabelBayar.getValueAt(bar, 2).toString());
        tglBayar.setText(tabelBayar.getValueAt(bar, 3).toString());
        tenggat.setText(tabelBayar.getValueAt(bar, 4).toString());
        totalbayar.setText(tabelBayar.getValueAt(bar, 5).toString());
        
    }//GEN-LAST:event_tabelBayarMouseClicked

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        inits();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        int bar = tabelBayar.getSelectedRow();
        int ok = JOptionPane.showConfirmDialog(null, "hapus","Konfirmasi Dialog",
            JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0){
            String sql = "delete from pembayaran where id_pembayaran='"+tabelBayar.getValueAt(bar, 0)+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                kosong();
                namaPelanggan.requestFocus();
                inits();
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus" +e);
            }
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        if (IDpembayaran.getText().length() == 0 || IDpelanggan.getText().length() == 0 ||
            namaPelanggan.getText().length() == 0 || tglBayar.getText().length() == 0 || 
                tenggat.getText().length() == 0 || totalbayar.getText().length() == 0){
            JOptionPane.showMessageDialog(this, "jangan kosong", "Pesan", JOptionPane.ERROR_MESSAGE);
        }else{
            Object[] values = {IDpembayaran.getText(), IDpelanggan.getText(),namaPelanggan.getText(),
                tglBayar.getText(), tenggat.getText(),totalbayar.getText()};

            String sql = "SELECT * FROM pembayaran WHERE id_pembayaran = '"+IDpembayaran.getText()+"'";
            commit = OlahData.commit(sql);
            try {
                if(commit.equals("update")){
                    OlahData.saveUpdate("normal",
                        "update pembayaran set id_pembayaran=?, id_pelanggan=?, nama_pelanggan=?,tgl_bayar=?, tenggat_waktu=?, total_bayar=? where id_pembayaran='"+IDpembayaran.getText()+"'",
                        values);
                }else if(commit.equals("save")){
                    OlahData.saveUpdate("normal", "INSERT INTO pembayaran VALUE (?,?,?,?,?,?)", values);
                    
                }
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");

                inits();
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Warning", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(datapaket.class.getName()).log(Level.SEVERE, null, e);
            }
            sql = null;
            commit = null;
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeActionPerformed
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        dispose();
        try {
            new menu_utama().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(menu_utama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_exitActionPerformed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        // TODO add your handling code here:
        setLocation (evt.getXOnScreen()-posX,evt.getYOnScreen()-posY);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        posX = evt.getX();
        posY = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void IDpelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IDpelangganMouseClicked
        String sql = "SELECT * FROM pelanggan";
        try {
            new popupData().setVisible(true);
            popupProperties.setSource("pelanggan");
            TableProperties.getColumns(sql);
            TableProperties.showData(pelanggan.Baris, popupData.tabData, sql);
        } catch (Exception ex) {
            Logger.getLogger(pembayaran.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_IDpelangganMouseClicked

    private void IDpembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDpembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDpembayaranActionPerformed

    private void IDpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDpelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDpelangganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new pembayaran().setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(pembayaran.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField IDpelanggan;
    public static javax.swing.JTextField IDpembayaran;
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton minimize;
    public static javax.swing.JTextField namaPelanggan;
    private javax.swing.JTable tabelBayar;
    private javax.swing.JTextField tenggat;
    public static javax.swing.JTextField tglBayar;
    private javax.swing.JTextField totalbayar;
    // End of variables declaration//GEN-END:variables
}

