package Forms;

import java.sql.*;
import java.util.logging.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import misc.*;
import properties.*;
import utils.Utils;

public class riwayatPem extends javax.swing.JFrame {
    private final Utils utils = new Utils();
    
     
    public riwayatPem() throws Exception{
        initComponents();
        inits();
    }
    
    int posX = 0, posY = 0;
    static String commit;
    private Connection conn = new koneksi().koneksiDatabase(); 
    private DefaultTableModel tabmode; 
    Object[] Baris = {"ID Bayar", "ID Pelanggan", "Nama", "Tanggal", "Tenggat", "Total"};
    
    private void inits(){
        
        String sql = "SELECT * FROM pembayaran";
        TableProperties.initTable(Baris, tabelPersediaan);
        TableProperties.getColumns(sql);
        TableProperties.showData(Baris, tabelPersediaan, sql);
        kosong();
    }

    protected void kosong(){        
                    
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPersediaan = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        minimize = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        reportPersediaan = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        searchTrans = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(840, 600));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(87, 131, 123));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Riwayat Pembayaran");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 92, 103)));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 50, 660, 40);

        tabelPersediaan.setForeground(new java.awt.Color(87, 131, 123));
        tabelPersediaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPersediaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPersediaanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPersediaan);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 180, 750, 310);

        jPanel5.setBackground(new java.awt.Color(0, 153, 204));
        jPanel5.setPreferredSize(new java.awt.Dimension(840, 40));
        jPanel5.setLayout(null);

        minimize.setBackground(new java.awt.Color(0, 153, 204));
        minimize.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        minimize.setForeground(java.awt.Color.white);
        minimize.setText("-");
        minimize.setBorderPainted(false);
        minimize.setFocusable(false);
        minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeActionPerformed(evt);
            }
        });
        jPanel5.add(minimize);
        minimize.setBounds(740, 0, 50, 40);

        exit.setBackground(new java.awt.Color(0, 153, 204));
        exit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        exit.setForeground(java.awt.Color.white);
        exit.setText("X");
        exit.setBorderPainted(false);
        exit.setFocusable(false);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel5.add(exit);
        exit.setBounds(790, 0, 50, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sistem Administrasi");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(0, 0, 150, 40);

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText(userSession.getNama());
        jPanel5.add(jLabel8);
        jLabel8.setBounds(160, 0, 130, 40);

        jSeparator2.setForeground(java.awt.Color.white);
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator2);
        jSeparator2.setBounds(150, 7, 10, 25);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 0, 840, 40);

        reportPersediaan.setBackground(new java.awt.Color(24, 77, 71));
        reportPersediaan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reportPersediaan.setForeground(new java.awt.Color(244, 244, 244));
        reportPersediaan.setText("BUAT LAPORAN ");
        reportPersediaan.setBorder(null);
        reportPersediaan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reportPersediaan.setPreferredSize(new java.awt.Dimension(110, 40));
        reportPersediaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportPersediaanActionPerformed(evt);
            }
        });
        jPanel1.add(reportPersediaan);
        reportPersediaan.setBounds(220, 530, 420, 40);

        jLabel29.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(87, 131, 123));
        jLabel29.setText(":");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(160, 140, 10, 30);

        jLabel32.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(87, 131, 123));
        jLabel32.setText("Cari Item");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(40, 140, 130, 30);

        searchTrans.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        searchTrans.setForeground(new java.awt.Color(87, 131, 123));
        searchTrans.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(87, 131, 123)));
        searchTrans.setPreferredSize(new java.awt.Dimension(55, 30));
        searchTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTransActionPerformed(evt);
            }
        });
        searchTrans.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTransKeyReleased(evt);
            }
        });
        jPanel1.add(searchTrans);
        searchTrans.setBounds(170, 140, 220, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 840, 600);

        setSize(new java.awt.Dimension(840, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelPersediaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPersediaanMouseClicked
        int bar = tabelPersediaan.getSelectedRow();
        String a = tabmode.getValueAt(bar, 1).toString();
        String b = tabmode.getValueAt(bar, 2).toString();
        String c = tabmode.getValueAt(bar, 3).toString();

        
    }//GEN-LAST:event_tabelPersediaanMouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        posX = evt.getX();
        posY = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        setLocation (evt.getXOnScreen()-posX,evt.getYOnScreen()-posY);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeActionPerformed
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        dispose();
        try {
            new menu_utama().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(menu_utama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_exitActionPerformed

    private void reportPersediaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportPersediaanActionPerformed
        utils.bukaLaporan("datapembayaran", conn);
    }//GEN-LAST:event_reportPersediaanActionPerformed

    private void searchTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTransActionPerformed

    private void searchTransKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTransKeyReleased
        String search = searchTrans.getText();
        String sql = "SELECT * FROM pembayaran WHERE id_pembayaran LIKE '%"+search+"%' "
                                                        + "OR nama_pelanggan LIKE '%"+search+"%' ";
        TableProperties.getColumns(sql);
        TableProperties.showData(Baris, tabelPersediaan, sql);
    }//GEN-LAST:event_searchTransKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(riwayatPem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(riwayatPem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(riwayatPem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(riwayatPem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new riwayatPem().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(riwayatPem.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton minimize;
    private javax.swing.JButton reportPersediaan;
    private javax.swing.JTextField searchTrans;
    private javax.swing.JTable tabelPersediaan;
    // End of variables declaration//GEN-END:variables
}